# Generated by Django 6.0.5 on 2026-05-16 17:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crianca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome completo')),
                ('data_nascimento', models.DateField(verbose_name='Data de nascimento')),
                ('escola', models.CharField(blank=True, max_length=200, verbose_name='Escola onde estuda')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Criança / Adolescente',
                'verbose_name_plural': 'Crianças / Adolescentes',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Responsavel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome completo')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone / WhatsApp')),
                ('vinculo', models.CharField(choices=[('mae', 'Mãe'), ('pai', 'Pai'), ('avo', 'Avó / Avô'), ('tio', 'Tio / Tia'), ('responsavel_legal', 'Responsável legal'), ('outro', 'Vizinho / Outro')], max_length=30, verbose_name='Vínculo com a criança')),
                ('bairro', models.CharField(blank=True, max_length=100, verbose_name='Bairro / Comunidade')),
                ('data_nascimento', models.DateField(blank=True, null=True, verbose_name='Data de nascimento')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Responsável',
                'verbose_name_plural': 'Responsáveis',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Atendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_protocolo', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Nº do atendimento')),
                ('tipo_demanda', models.CharField(choices=[('violencia_fisica', 'Violência física'), ('violencia_psicologica', 'Violência psicológica'), ('negligencia', 'Negligência'), ('abandono', 'Abandono'), ('evasao_escolar', 'Evasão escolar'), ('abuso_sexual', 'Abuso sexual'), ('trabalho_infantil', 'Trabalho infantil'), ('outro', 'Outro')], max_length=30, verbose_name='Tipo de demanda')),
                ('descricao', models.TextField(verbose_name='Descrição do atendimento')),
                ('encaminhamento', models.CharField(blank=True, choices=[('', 'Nenhum por enquanto'), ('cras', 'CRAS'), ('creas', 'CREAS'), ('ubs', 'UBS / Posto de saúde'), ('delegacia', 'Delegacia'), ('escola', 'Escola'), ('mp', 'Ministério Público'), ('outro', 'Outro')], max_length=30, verbose_name='Encaminhamento realizado')),
                ('status', models.CharField(choices=[('aberto', 'Aberto'), ('em_andamento', 'Em andamento'), ('encerrado', 'Encerrado')], default='aberto', max_length=20, verbose_name='Status')),
                ('data_hora', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data e hora')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('crianca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atendimentos', to='atendimentos.crianca', verbose_name='Criança / Adolescente')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atendimentos', to='atendimentos.responsavel', verbose_name='Responsável')),
            ],
            options={
                'verbose_name': 'Atendimento',
                'verbose_name_plural': 'Atendimentos',
                'ordering': ['-data_hora'],
            },
        ),
    ]
